// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEKeyValueCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class CacheKey implements Cloneable,
                                 java.io.Serializable
{
    public CacheBusinessType cacheBusinessType;

    public CacheBusinessType getCacheBusinessType()
    {
        return cacheBusinessType;
    }

    public void setCacheBusinessType(CacheBusinessType cacheBusinessType)
    {
        this.cacheBusinessType = cacheBusinessType;
    }

    public String uniqueKey;

    public String getUniqueKey()
    {
        return uniqueKey;
    }

    public void setUniqueKey(String uniqueKey)
    {
        this.uniqueKey = uniqueKey;
    }

    public CacheKey()
    {
        this.cacheBusinessType = CacheBusinessType.E_AUTH;
        this.uniqueKey = "";
    }

    public CacheKey(CacheBusinessType cacheBusinessType, String uniqueKey)
    {
        this.cacheBusinessType = cacheBusinessType;
        this.uniqueKey = uniqueKey;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        CacheKey r = null;
        if(rhs instanceof CacheKey)
        {
            r = (CacheKey)rhs;
        }

        if(r != null)
        {
            if(this.cacheBusinessType != r.cacheBusinessType)
            {
                if(this.cacheBusinessType == null || r.cacheBusinessType == null || !this.cacheBusinessType.equals(r.cacheBusinessType))
                {
                    return false;
                }
            }
            if(this.uniqueKey != r.uniqueKey)
            {
                if(this.uniqueKey == null || r.uniqueKey == null || !this.uniqueKey.equals(r.uniqueKey))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::CacheKey");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, cacheBusinessType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, uniqueKey);
        return h_;
    }

    public CacheKey clone()
    {
        CacheKey c = null;
        try
        {
            c = (CacheKey)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        CacheBusinessType.ice_write(ostr, this.cacheBusinessType);
        ostr.writeString(this.uniqueKey);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.cacheBusinessType = CacheBusinessType.ice_read(istr);
        this.uniqueKey = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, CacheKey v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public CacheKey ice_read(com.zeroc.Ice.InputStream istr)
    {
        CacheKey v = new CacheKey();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<CacheKey> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, CacheKey v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<CacheKey> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(CacheKey.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final CacheKey _nullMarshalValue = new CacheKey();

    public static final long serialVersionUID = 1775995415L;
}
