// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCExtd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class DCAddLscpRtSnoReq implements Cloneable,
                                          java.io.Serializable
{
    public long devid;

    public long getDevid()
    {
        return devid;
    }

    public void setDevid(long devid)
    {
        this.devid = devid;
    }

    public String rtSno;

    public String getRtSno()
    {
        return rtSno;
    }

    public void setRtSno(String rtSno)
    {
        this.rtSno = rtSno;
    }

    public long dbid;

    public long getDbid()
    {
        return dbid;
    }

    public void setDbid(long dbid)
    {
        this.dbid = dbid;
    }

    public DCAddLscpRtSnoReq()
    {
        this.rtSno = "";
    }

    public DCAddLscpRtSnoReq(long devid, String rtSno, long dbid)
    {
        this.devid = devid;
        this.rtSno = rtSno;
        this.dbid = dbid;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DCAddLscpRtSnoReq r = null;
        if(rhs instanceof DCAddLscpRtSnoReq)
        {
            r = (DCAddLscpRtSnoReq)rhs;
        }

        if(r != null)
        {
            if(this.devid != r.devid)
            {
                return false;
            }
            if(this.rtSno != r.rtSno)
            {
                if(this.rtSno == null || r.rtSno == null || !this.rtSno.equals(r.rtSno))
                {
                    return false;
                }
            }
            if(this.dbid != r.dbid)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::DCAddLscpRtSnoReq");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, devid);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rtSno);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, dbid);
        return h_;
    }

    public DCAddLscpRtSnoReq clone()
    {
        DCAddLscpRtSnoReq c = null;
        try
        {
            c = (DCAddLscpRtSnoReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.devid);
        ostr.writeString(this.rtSno);
        ostr.writeLong(this.dbid);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.devid = istr.readLong();
        this.rtSno = istr.readString();
        this.dbid = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DCAddLscpRtSnoReq v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DCAddLscpRtSnoReq ice_read(com.zeroc.Ice.InputStream istr)
    {
        DCAddLscpRtSnoReq v = new DCAddLscpRtSnoReq();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DCAddLscpRtSnoReq> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DCAddLscpRtSnoReq v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<DCAddLscpRtSnoReq> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(DCAddLscpRtSnoReq.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DCAddLscpRtSnoReq _nullMarshalValue = new DCAddLscpRtSnoReq();

    public static final long serialVersionUID = 269091424L;
}
