// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCExtd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class DCDelAccountName2UUIDReq implements Cloneable,
                                                 java.io.Serializable
{
    public String user;

    public String getUser()
    {
        return user;
    }

    public void setUser(String user)
    {
        this.user = user;
    }

    public DCDelAccountName2UUIDReq()
    {
        this.user = "";
    }

    public DCDelAccountName2UUIDReq(String user)
    {
        this.user = user;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DCDelAccountName2UUIDReq r = null;
        if(rhs instanceof DCDelAccountName2UUIDReq)
        {
            r = (DCDelAccountName2UUIDReq)rhs;
        }

        if(r != null)
        {
            if(this.user != r.user)
            {
                if(this.user == null || r.user == null || !this.user.equals(r.user))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::DCDelAccountName2UUIDReq");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, user);
        return h_;
    }

    public DCDelAccountName2UUIDReq clone()
    {
        DCDelAccountName2UUIDReq c = null;
        try
        {
            c = (DCDelAccountName2UUIDReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.user);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.user = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DCDelAccountName2UUIDReq v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DCDelAccountName2UUIDReq ice_read(com.zeroc.Ice.InputStream istr)
    {
        DCDelAccountName2UUIDReq v = new DCDelAccountName2UUIDReq();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DCDelAccountName2UUIDReq> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DCDelAccountName2UUIDReq v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<DCDelAccountName2UUIDReq> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(DCDelAccountName2UUIDReq.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DCDelAccountName2UUIDReq _nullMarshalValue = new DCDelAccountName2UUIDReq();

    public static final long serialVersionUID = -645761607L;
}
