// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCExtd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class DCExtdPack implements Cloneable,
                                   java.io.Serializable
{
    public RPCHeader rpcHeader;

    public RPCHeader getRpcHeader()
    {
        return rpcHeader;
    }

    public void setRpcHeader(RPCHeader rpcHeader)
    {
        this.rpcHeader = rpcHeader;
    }

    public DCExtdCmd dcExtdCmd;

    public DCExtdCmd getDcExtdCmd()
    {
        return dcExtdCmd;
    }

    public void setDcExtdCmd(DCExtdCmd dcExtdCmd)
    {
        this.dcExtdCmd = dcExtdCmd;
    }

    public byte[] body;

    public byte[] getBody()
    {
        return body;
    }

    public void setBody(byte[] body)
    {
        this.body = body;
    }

    public byte getBody(int index)
    {
        return this.body[index];
    }

    public void setBody(int index, byte val)
    {
        this.body[index] = val;
    }

    public DCExtdPack()
    {
        this.rpcHeader = new RPCHeader();
        this.dcExtdCmd = DCExtdCmd.E_DCEXTDCMD_ERROR;
    }

    public DCExtdPack(RPCHeader rpcHeader, DCExtdCmd dcExtdCmd, byte[] body)
    {
        this.rpcHeader = rpcHeader;
        this.dcExtdCmd = dcExtdCmd;
        this.body = body;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DCExtdPack r = null;
        if(rhs instanceof DCExtdPack)
        {
            r = (DCExtdPack)rhs;
        }

        if(r != null)
        {
            if(this.rpcHeader != r.rpcHeader)
            {
                if(this.rpcHeader == null || r.rpcHeader == null || !this.rpcHeader.equals(r.rpcHeader))
                {
                    return false;
                }
            }
            if(this.dcExtdCmd != r.dcExtdCmd)
            {
                if(this.dcExtdCmd == null || r.dcExtdCmd == null || !this.dcExtdCmd.equals(r.dcExtdCmd))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(this.body, r.body))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::DCExtdPack");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rpcHeader);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, dcExtdCmd);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, body);
        return h_;
    }

    public DCExtdPack clone()
    {
        DCExtdPack c = null;
        try
        {
            c = (DCExtdPack)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        RPCHeader.ice_write(ostr, this.rpcHeader);
        DCExtdCmd.ice_write(ostr, this.dcExtdCmd);
        ostr.writeByteSeq(this.body);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.rpcHeader = RPCHeader.ice_read(istr);
        this.dcExtdCmd = DCExtdCmd.ice_read(istr);
        this.body = istr.readByteSeq();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DCExtdPack v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DCExtdPack ice_read(com.zeroc.Ice.InputStream istr)
    {
        DCExtdPack v = new DCExtdPack();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DCExtdPack> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DCExtdPack v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<DCExtdPack> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(DCExtdPack.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DCExtdPack _nullMarshalValue = new DCExtdPack();

    public static final long serialVersionUID = -307868128L;
}
