// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCExtd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class DCGetLockedListResp implements Cloneable,
                                            java.io.Serializable
{
    public IdInfo[] idInfoSeq;

    public IdInfo[] getIdInfoSeq()
    {
        return idInfoSeq;
    }

    public void setIdInfoSeq(IdInfo[] idInfoSeq)
    {
        this.idInfoSeq = idInfoSeq;
    }

    public IdInfo getIdInfoSeq(int index)
    {
        return this.idInfoSeq[index];
    }

    public void setIdInfoSeq(int index, IdInfo val)
    {
        this.idInfoSeq[index] = val;
    }

    public DCGetLockedListResp()
    {
    }

    public DCGetLockedListResp(IdInfo[] idInfoSeq)
    {
        this.idInfoSeq = idInfoSeq;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DCGetLockedListResp r = null;
        if(rhs instanceof DCGetLockedListResp)
        {
            r = (DCGetLockedListResp)rhs;
        }

        if(r != null)
        {
            if(!java.util.Arrays.equals(this.idInfoSeq, r.idInfoSeq))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::DCGetLockedListResp");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, idInfoSeq);
        return h_;
    }

    public DCGetLockedListResp clone()
    {
        DCGetLockedListResp c = null;
        try
        {
            c = (DCGetLockedListResp)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        IdInfoSeqHelper.write(ostr, this.idInfoSeq);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.idInfoSeq = IdInfoSeqHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DCGetLockedListResp v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DCGetLockedListResp ice_read(com.zeroc.Ice.InputStream istr)
    {
        DCGetLockedListResp v = new DCGetLockedListResp();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DCGetLockedListResp> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DCGetLockedListResp v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<DCGetLockedListResp> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(DCGetLockedListResp.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DCGetLockedListResp _nullMarshalValue = new DCGetLockedListResp();

    public static final long serialVersionUID = -1744777132L;
}
