// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCExtd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class DCGetAccountStatusResp implements Cloneable,
                                               java.io.Serializable
{
    public DCAccoutStatus[] dcAccoutStatusSeq;

    public DCAccoutStatus[] getDcAccoutStatusSeq()
    {
        return dcAccoutStatusSeq;
    }

    public void setDcAccoutStatusSeq(DCAccoutStatus[] dcAccoutStatusSeq)
    {
        this.dcAccoutStatusSeq = dcAccoutStatusSeq;
    }

    public DCAccoutStatus getDcAccoutStatusSeq(int index)
    {
        return this.dcAccoutStatusSeq[index];
    }

    public void setDcAccoutStatusSeq(int index, DCAccoutStatus val)
    {
        this.dcAccoutStatusSeq[index] = val;
    }

    public DCGetAccountStatusResp()
    {
    }

    public DCGetAccountStatusResp(DCAccoutStatus[] dcAccoutStatusSeq)
    {
        this.dcAccoutStatusSeq = dcAccoutStatusSeq;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DCGetAccountStatusResp r = null;
        if(rhs instanceof DCGetAccountStatusResp)
        {
            r = (DCGetAccountStatusResp)rhs;
        }

        if(r != null)
        {
            if(!java.util.Arrays.equals(this.dcAccoutStatusSeq, r.dcAccoutStatusSeq))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::DCGetAccountStatusResp");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, dcAccoutStatusSeq);
        return h_;
    }

    public DCGetAccountStatusResp clone()
    {
        DCGetAccountStatusResp c = null;
        try
        {
            c = (DCGetAccountStatusResp)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        DCAccoutStatusSeqHelper.write(ostr, this.dcAccoutStatusSeq);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.dcAccoutStatusSeq = DCAccoutStatusSeqHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DCGetAccountStatusResp v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DCGetAccountStatusResp ice_read(com.zeroc.Ice.InputStream istr)
    {
        DCGetAccountStatusResp v = new DCGetAccountStatusResp();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DCGetAccountStatusResp> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DCGetAccountStatusResp v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<DCGetAccountStatusResp> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(DCGetAccountStatusResp.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DCGetAccountStatusResp _nullMarshalValue = new DCGetAccountStatusResp();

    public static final long serialVersionUID = 938800758L;
}
