// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCExtd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class DCGetLscpSession2UUIDResp implements Cloneable,
                                                  java.io.Serializable
{
    public long uuid;

    public long getUuid()
    {
        return uuid;
    }

    public void setUuid(long uuid)
    {
        this.uuid = uuid;
    }

    public DCGetLscpSession2UUIDResp()
    {
        this.uuid = 0L;
    }

    public DCGetLscpSession2UUIDResp(long uuid)
    {
        this.uuid = uuid;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DCGetLscpSession2UUIDResp r = null;
        if(rhs instanceof DCGetLscpSession2UUIDResp)
        {
            r = (DCGetLscpSession2UUIDResp)rhs;
        }

        if(r != null)
        {
            if(this.uuid != r.uuid)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::DCGetLscpSession2UUIDResp");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, uuid);
        return h_;
    }

    public DCGetLscpSession2UUIDResp clone()
    {
        DCGetLscpSession2UUIDResp c = null;
        try
        {
            c = (DCGetLscpSession2UUIDResp)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.uuid);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.uuid = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DCGetLscpSession2UUIDResp v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DCGetLscpSession2UUIDResp ice_read(com.zeroc.Ice.InputStream istr)
    {
        DCGetLscpSession2UUIDResp v = new DCGetLscpSession2UUIDResp();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DCGetLscpSession2UUIDResp> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DCGetLscpSession2UUIDResp v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(8);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<DCGetLscpSession2UUIDResp> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(DCGetLscpSession2UUIDResp.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DCGetLscpSession2UUIDResp _nullMarshalValue = new DCGetLscpSession2UUIDResp();

    public static final long serialVersionUID = 18582840L;
}
