// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCExtd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class DCGetAccountName2UUIDResp implements Cloneable,
                                                  java.io.Serializable
{
    public IdInfo idInfo;

    public IdInfo getIdInfo()
    {
        return idInfo;
    }

    public void setIdInfo(IdInfo idInfo)
    {
        this.idInfo = idInfo;
    }

    public DCGetAccountName2UUIDResp()
    {
        this.idInfo = new IdInfo();
    }

    public DCGetAccountName2UUIDResp(IdInfo idInfo)
    {
        this.idInfo = idInfo;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DCGetAccountName2UUIDResp r = null;
        if(rhs instanceof DCGetAccountName2UUIDResp)
        {
            r = (DCGetAccountName2UUIDResp)rhs;
        }

        if(r != null)
        {
            if(this.idInfo != r.idInfo)
            {
                if(this.idInfo == null || r.idInfo == null || !this.idInfo.equals(r.idInfo))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::DCGetAccountName2UUIDResp");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, idInfo);
        return h_;
    }

    public DCGetAccountName2UUIDResp clone()
    {
        DCGetAccountName2UUIDResp c = null;
        try
        {
            c = (DCGetAccountName2UUIDResp)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        IdInfo.ice_write(ostr, this.idInfo);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.idInfo = IdInfo.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DCGetAccountName2UUIDResp v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DCGetAccountName2UUIDResp ice_read(com.zeroc.Ice.InputStream istr)
    {
        DCGetAccountName2UUIDResp v = new DCGetAccountName2UUIDResp();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DCGetAccountName2UUIDResp> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DCGetAccountName2UUIDResp v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<DCGetAccountName2UUIDResp> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(DCGetAccountName2UUIDResp.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DCGetAccountName2UUIDResp _nullMarshalValue = new DCGetAccountName2UUIDResp();

    public static final long serialVersionUID = -2010914206L;
}
