// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCExtd.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class DCSetAccountName2UUIDReq implements Cloneable,
                                                 java.io.Serializable
{
    public String user;

    public String getUser()
    {
        return user;
    }

    public void setUser(String user)
    {
        this.user = user;
    }

    public IdInfo idInfo;

    public IdInfo getIdInfo()
    {
        return idInfo;
    }

    public void setIdInfo(IdInfo idInfo)
    {
        this.idInfo = idInfo;
    }

    public DCSetAccountName2UUIDReq()
    {
        this.user = "";
        this.idInfo = new IdInfo();
    }

    public DCSetAccountName2UUIDReq(String user, IdInfo idInfo)
    {
        this.user = user;
        this.idInfo = idInfo;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        DCSetAccountName2UUIDReq r = null;
        if(rhs instanceof DCSetAccountName2UUIDReq)
        {
            r = (DCSetAccountName2UUIDReq)rhs;
        }

        if(r != null)
        {
            if(this.user != r.user)
            {
                if(this.user == null || r.user == null || !this.user.equals(r.user))
                {
                    return false;
                }
            }
            if(this.idInfo != r.idInfo)
            {
                if(this.idInfo == null || r.idInfo == null || !this.idInfo.equals(r.idInfo))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::DCSetAccountName2UUIDReq");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, user);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, idInfo);
        return h_;
    }

    public DCSetAccountName2UUIDReq clone()
    {
        DCSetAccountName2UUIDReq c = null;
        try
        {
            c = (DCSetAccountName2UUIDReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.user);
        IdInfo.ice_write(ostr, this.idInfo);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.user = istr.readString();
        this.idInfo = IdInfo.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, DCSetAccountName2UUIDReq v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public DCSetAccountName2UUIDReq ice_read(com.zeroc.Ice.InputStream istr)
    {
        DCSetAccountName2UUIDReq v = new DCSetAccountName2UUIDReq();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<DCSetAccountName2UUIDReq> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, DCSetAccountName2UUIDReq v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<DCSetAccountName2UUIDReq> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(DCSetAccountName2UUIDReq.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final DCSetAccountName2UUIDReq _nullMarshalValue = new DCSetAccountName2UUIDReq();

    public static final long serialVersionUID = -524802638L;
}
