// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEFilePack.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class FilePack implements Cloneable,
                                 java.io.Serializable
{
    public RPCHeader rpcHeader;

    public RPCHeader getRpcHeader()
    {
        return rpcHeader;
    }

    public void setRpcHeader(RPCHeader rpcHeader)
    {
        this.rpcHeader = rpcHeader;
    }

    public FSCmd fsCmd;

    public FSCmd getFsCmd()
    {
        return fsCmd;
    }

    public void setFsCmd(FSCmd fsCmd)
    {
        this.fsCmd = fsCmd;
    }

    public byte[] body;

    public byte[] getBody()
    {
        return body;
    }

    public void setBody(byte[] body)
    {
        this.body = body;
    }

    public byte getBody(int index)
    {
        return this.body[index];
    }

    public void setBody(int index, byte val)
    {
        this.body[index] = val;
    }

    public FilePack()
    {
        this.rpcHeader = new RPCHeader();
        this.fsCmd = FSCmd.E_FSCMD_CS_SET;
    }

    public FilePack(RPCHeader rpcHeader, FSCmd fsCmd, byte[] body)
    {
        this.rpcHeader = rpcHeader;
        this.fsCmd = fsCmd;
        this.body = body;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        FilePack r = null;
        if(rhs instanceof FilePack)
        {
            r = (FilePack)rhs;
        }

        if(r != null)
        {
            if(this.rpcHeader != r.rpcHeader)
            {
                if(this.rpcHeader == null || r.rpcHeader == null || !this.rpcHeader.equals(r.rpcHeader))
                {
                    return false;
                }
            }
            if(this.fsCmd != r.fsCmd)
            {
                if(this.fsCmd == null || r.fsCmd == null || !this.fsCmd.equals(r.fsCmd))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(this.body, r.body))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::FilePack");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rpcHeader);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fsCmd);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, body);
        return h_;
    }

    public FilePack clone()
    {
        FilePack c = null;
        try
        {
            c = (FilePack)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        RPCHeader.ice_write(ostr, this.rpcHeader);
        FSCmd.ice_write(ostr, this.fsCmd);
        ostr.writeByteSeq(this.body);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.rpcHeader = RPCHeader.ice_read(istr);
        this.fsCmd = FSCmd.ice_read(istr);
        this.body = istr.readByteSeq();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, FilePack v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public FilePack ice_read(com.zeroc.Ice.InputStream istr)
    {
        FilePack v = new FilePack();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<FilePack> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, FilePack v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<FilePack> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(FilePack.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final FilePack _nullMarshalValue = new FilePack();

    public static final long serialVersionUID = 1025093715L;
}
