// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEFilePack.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public enum FSCmd implements java.io.Serializable
{
    E_FSCMD_CS_SET(1),
    E_FSCMD_CS_GET(2),
    E_FSCMD_CS_DEL(3),
    E_FSCMD_SC_SET(1001),
    E_FSCMD_SC_GET(1002),
    E_FSCMD_SC_DEL(1003);

    public int value()
    {
        return _value;
    }

    public static FSCmd valueOf(int v)
    {
        switch(v)
        {
        case 1:
            return E_FSCMD_CS_SET;
        case 2:
            return E_FSCMD_CS_GET;
        case 3:
            return E_FSCMD_CS_DEL;
        case 1001:
            return E_FSCMD_SC_SET;
        case 1002:
            return E_FSCMD_SC_GET;
        case 1003:
            return E_FSCMD_SC_DEL;
        }
        return null;
    }

    private FSCmd(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 1003);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, FSCmd v)
    {
        if(v == null)
        {
            ostr.writeEnum(FSCmd.E_FSCMD_CS_SET.value(), 1003);
        }
        else
        {
            ostr.writeEnum(v.value(), 1003);
        }
    }

    public static FSCmd ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(1003);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<FSCmd> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, FSCmd v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<FSCmd> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static FSCmd validate(int v)
    {
        final FSCmd e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
