// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEKeyValueCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class GetCacheReq implements Cloneable,
                                    java.io.Serializable
{
    public RPCHeader rpcHeader;

    public RPCHeader getRpcHeader()
    {
        return rpcHeader;
    }

    public void setRpcHeader(RPCHeader rpcHeader)
    {
        this.rpcHeader = rpcHeader;
    }

    public CacheKey cacheKey;

    public CacheKey getCacheKey()
    {
        return cacheKey;
    }

    public void setCacheKey(CacheKey cacheKey)
    {
        this.cacheKey = cacheKey;
    }

    public GetCacheReq()
    {
        this.rpcHeader = new RPCHeader();
        this.cacheKey = new CacheKey();
    }

    public GetCacheReq(RPCHeader rpcHeader, CacheKey cacheKey)
    {
        this.rpcHeader = rpcHeader;
        this.cacheKey = cacheKey;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GetCacheReq r = null;
        if(rhs instanceof GetCacheReq)
        {
            r = (GetCacheReq)rhs;
        }

        if(r != null)
        {
            if(this.rpcHeader != r.rpcHeader)
            {
                if(this.rpcHeader == null || r.rpcHeader == null || !this.rpcHeader.equals(r.rpcHeader))
                {
                    return false;
                }
            }
            if(this.cacheKey != r.cacheKey)
            {
                if(this.cacheKey == null || r.cacheKey == null || !this.cacheKey.equals(r.cacheKey))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::GetCacheReq");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rpcHeader);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, cacheKey);
        return h_;
    }

    public GetCacheReq clone()
    {
        GetCacheReq c = null;
        try
        {
            c = (GetCacheReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        RPCHeader.ice_write(ostr, this.rpcHeader);
        CacheKey.ice_write(ostr, this.cacheKey);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.rpcHeader = RPCHeader.ice_read(istr);
        this.cacheKey = CacheKey.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, GetCacheReq v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public GetCacheReq ice_read(com.zeroc.Ice.InputStream istr)
    {
        GetCacheReq v = new GetCacheReq();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GetCacheReq> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, GetCacheReq v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<GetCacheReq> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(GetCacheReq.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final GetCacheReq _nullMarshalValue = new GetCacheReq();

    public static final long serialVersionUID = 553556323L;
}
