// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEStatus.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public final class LoginStatusSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, LoginStatus[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                LoginStatus.ice_write(ostr, v[i0]);
            }
        }
    }

    public static LoginStatus[] read(com.zeroc.Ice.InputStream istr)
    {
        final LoginStatus[] v;
        final int len0 = istr.readAndCheckSeqSize(10);
        v = new LoginStatus[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = LoginStatus.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LoginStatus[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, LoginStatus[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 10 + 5 : optSize * 10 + 1);
            LoginStatusSeqHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<LoginStatus[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            LoginStatus[] v;
            v = LoginStatusSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
