// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEStatus.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class LoginStatus implements Cloneable,
                                    java.io.Serializable
{
    public boolean isValid;

    public boolean getIsValid()
    {
        return isValid;
    }

    public void setIsValid(boolean isValid)
    {
        this.isValid = isValid;
    }

    public boolean isIsValid()
    {
        return isValid;
    }

    public boolean isOnline;

    public boolean getIsOnline()
    {
        return isOnline;
    }

    public void setIsOnline(boolean isOnline)
    {
        this.isOnline = isOnline;
    }

    public boolean isIsOnline()
    {
        return isOnline;
    }

    public long latestOnOffLineTime;

    public long getLatestOnOffLineTime()
    {
        return latestOnOffLineTime;
    }

    public void setLatestOnOffLineTime(long latestOnOffLineTime)
    {
        this.latestOnOffLineTime = latestOnOffLineTime;
    }

    public LoginStatus()
    {
        this.isValid = true;
        this.isOnline = true;
        this.latestOnOffLineTime = 0L;
    }

    public LoginStatus(boolean isValid, boolean isOnline, long latestOnOffLineTime)
    {
        this.isValid = isValid;
        this.isOnline = isOnline;
        this.latestOnOffLineTime = latestOnOffLineTime;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LoginStatus r = null;
        if(rhs instanceof LoginStatus)
        {
            r = (LoginStatus)rhs;
        }

        if(r != null)
        {
            if(this.isValid != r.isValid)
            {
                return false;
            }
            if(this.isOnline != r.isOnline)
            {
                return false;
            }
            if(this.latestOnOffLineTime != r.latestOnOffLineTime)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::LoginStatus");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isValid);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, isOnline);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latestOnOffLineTime);
        return h_;
    }

    public LoginStatus clone()
    {
        LoginStatus c = null;
        try
        {
            c = (LoginStatus)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeBool(this.isValid);
        ostr.writeBool(this.isOnline);
        ostr.writeLong(this.latestOnOffLineTime);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.isValid = istr.readBool();
        this.isOnline = istr.readBool();
        this.latestOnOffLineTime = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, LoginStatus v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public LoginStatus ice_read(com.zeroc.Ice.InputStream istr)
    {
        LoginStatus v = new LoginStatus();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LoginStatus> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LoginStatus v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(10);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<LoginStatus> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(LoginStatus.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final LoginStatus _nullMarshalValue = new LoginStatus();

    public static final long serialVersionUID = 865989661L;
}
