// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEStatus.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public final class LoginStatusDictHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, java.util.Map<Long, LoginStatus> v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.size());
            for(java.util.Map.Entry<Long, LoginStatus> e : v.entrySet())
            {
                ostr.writeLong(e.getKey());
                LoginStatus.ice_write(ostr, e.getValue());
            }
        }
    }

    public static java.util.Map<Long, LoginStatus> read(com.zeroc.Ice.InputStream istr)
    {
        java.util.Map<Long, LoginStatus> v;
        v = new java.util.HashMap<Long, LoginStatus>();
        int sz0 = istr.readSize();
        for(int i0 = 0; i0 < sz0; i0++)
        {
            long key;
            key = istr.readLong();
            LoginStatus value;
            value = LoginStatus.ice_read(istr);
            v.put(key, value);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<java.util.Map<Long, LoginStatus>> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Map<Long, LoginStatus> v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.size();
            ostr.writeSize(optSize > 254 ? optSize * 18 + 5 : optSize * 18 + 1);
            LoginStatusDictHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<java.util.Map<Long, LoginStatus>> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            java.util.Map<Long, LoginStatus> v;
            v = LoginStatusDictHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
