// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEELscpProtocal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class LscpRTHeader implements Cloneable,
                                     java.io.Serializable
{
    public LSCP_RT_DATA_TYPE rt_data_type;

    public LSCP_RT_DATA_TYPE getRt_data_type()
    {
        return rt_data_type;
    }

    public void setRt_data_type(LSCP_RT_DATA_TYPE rt_data_type)
    {
        this.rt_data_type = rt_data_type;
    }

    public LscpUniqSNo lscpUniqSNo;

    public LscpUniqSNo getLscpUniqSNo()
    {
        return lscpUniqSNo;
    }

    public void setLscpUniqSNo(LscpUniqSNo lscpUniqSNo)
    {
        this.lscpUniqSNo = lscpUniqSNo;
    }

    public LscpRTHeader()
    {
        this.rt_data_type = LSCP_RT_DATA_TYPE.E_RT_DATA_TYPE_WARNING;
        this.lscpUniqSNo = new LscpUniqSNo();
    }

    public LscpRTHeader(LSCP_RT_DATA_TYPE rt_data_type, LscpUniqSNo lscpUniqSNo)
    {
        this.rt_data_type = rt_data_type;
        this.lscpUniqSNo = lscpUniqSNo;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LscpRTHeader r = null;
        if(rhs instanceof LscpRTHeader)
        {
            r = (LscpRTHeader)rhs;
        }

        if(r != null)
        {
            if(this.rt_data_type != r.rt_data_type)
            {
                if(this.rt_data_type == null || r.rt_data_type == null || !this.rt_data_type.equals(r.rt_data_type))
                {
                    return false;
                }
            }
            if(this.lscpUniqSNo != r.lscpUniqSNo)
            {
                if(this.lscpUniqSNo == null || r.lscpUniqSNo == null || !this.lscpUniqSNo.equals(r.lscpUniqSNo))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::LscpRTHeader");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, rt_data_type);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lscpUniqSNo);
        return h_;
    }

    public LscpRTHeader clone()
    {
        LscpRTHeader c = null;
        try
        {
            c = (LscpRTHeader)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        LSCP_RT_DATA_TYPE.ice_write(ostr, this.rt_data_type);
        LscpUniqSNo.ice_write(ostr, this.lscpUniqSNo);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.rt_data_type = LSCP_RT_DATA_TYPE.ice_read(istr);
        this.lscpUniqSNo = LscpUniqSNo.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, LscpRTHeader v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public LscpRTHeader ice_read(com.zeroc.Ice.InputStream istr)
    {
        LscpRTHeader v = new LscpRTHeader();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LscpRTHeader> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LscpRTHeader v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<LscpRTHeader> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(LscpRTHeader.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final LscpRTHeader _nullMarshalValue = new LscpRTHeader();

    public static final long serialVersionUID = -1895669348L;
}
