// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEELscpProtocal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class LscpGetFileReq implements Cloneable,
                                       java.io.Serializable
{
    public String fileKey;

    public String getFileKey()
    {
        return fileKey;
    }

    public void setFileKey(String fileKey)
    {
        this.fileKey = fileKey;
    }

    public LscpGetFileReq()
    {
        this.fileKey = "";
    }

    public LscpGetFileReq(String fileKey)
    {
        this.fileKey = fileKey;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LscpGetFileReq r = null;
        if(rhs instanceof LscpGetFileReq)
        {
            r = (LscpGetFileReq)rhs;
        }

        if(r != null)
        {
            if(this.fileKey != r.fileKey)
            {
                if(this.fileKey == null || r.fileKey == null || !this.fileKey.equals(r.fileKey))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::LscpGetFileReq");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fileKey);
        return h_;
    }

    public LscpGetFileReq clone()
    {
        LscpGetFileReq c = null;
        try
        {
            c = (LscpGetFileReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.fileKey);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.fileKey = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, LscpGetFileReq v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public LscpGetFileReq ice_read(com.zeroc.Ice.InputStream istr)
    {
        LscpGetFileReq v = new LscpGetFileReq();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LscpGetFileReq> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LscpGetFileReq v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<LscpGetFileReq> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(LscpGetFileReq.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final LscpGetFileReq _nullMarshalValue = new LscpGetFileReq();

    public static final long serialVersionUID = 2103692022L;
}
