// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEELscpProtocal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class LscpRTPackAck implements Cloneable,
                                      java.io.Serializable
{
    public LscpRTHeader lscpRTHeader;

    public LscpRTHeader getLscpRTHeader()
    {
        return lscpRTHeader;
    }

    public void setLscpRTHeader(LscpRTHeader lscpRTHeader)
    {
        this.lscpRTHeader = lscpRTHeader;
    }

    public LscpRTPackAck()
    {
        this.lscpRTHeader = new LscpRTHeader();
    }

    public LscpRTPackAck(LscpRTHeader lscpRTHeader)
    {
        this.lscpRTHeader = lscpRTHeader;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LscpRTPackAck r = null;
        if(rhs instanceof LscpRTPackAck)
        {
            r = (LscpRTPackAck)rhs;
        }

        if(r != null)
        {
            if(this.lscpRTHeader != r.lscpRTHeader)
            {
                if(this.lscpRTHeader == null || r.lscpRTHeader == null || !this.lscpRTHeader.equals(r.lscpRTHeader))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::LscpRTPackAck");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lscpRTHeader);
        return h_;
    }

    public LscpRTPackAck clone()
    {
        LscpRTPackAck c = null;
        try
        {
            c = (LscpRTPackAck)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        LscpRTHeader.ice_write(ostr, this.lscpRTHeader);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.lscpRTHeader = LscpRTHeader.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, LscpRTPackAck v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public LscpRTPackAck ice_read(com.zeroc.Ice.InputStream istr)
    {
        LscpRTPackAck v = new LscpRTPackAck();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LscpRTPackAck> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LscpRTPackAck v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<LscpRTPackAck> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(LscpRTPackAck.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final LscpRTPackAck _nullMarshalValue = new LscpRTPackAck();

    public static final long serialVersionUID = -1058832910L;
}
