// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEELscpProtocal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class LscpUniqSNo implements Cloneable,
                                    java.io.Serializable
{
    public long persistenceSno;

    public long getPersistenceSno()
    {
        return persistenceSno;
    }

    public void setPersistenceSno(long persistenceSno)
    {
        this.persistenceSno = persistenceSno;
    }

    public long bdSNo;

    public long getBdSNo()
    {
        return bdSNo;
    }

    public void setBdSNo(long bdSNo)
    {
        this.bdSNo = bdSNo;
    }

    public long time;

    public long getTime()
    {
        return time;
    }

    public void setTime(long time)
    {
        this.time = time;
    }

    public LscpUniqSNo()
    {
        this.persistenceSno = 0L;
        this.bdSNo = 0L;
        this.time = 0L;
    }

    public LscpUniqSNo(long persistenceSno, long bdSNo, long time)
    {
        this.persistenceSno = persistenceSno;
        this.bdSNo = bdSNo;
        this.time = time;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LscpUniqSNo r = null;
        if(rhs instanceof LscpUniqSNo)
        {
            r = (LscpUniqSNo)rhs;
        }

        if(r != null)
        {
            if(this.persistenceSno != r.persistenceSno)
            {
                return false;
            }
            if(this.bdSNo != r.bdSNo)
            {
                return false;
            }
            if(this.time != r.time)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::LscpUniqSNo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, persistenceSno);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, bdSNo);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, time);
        return h_;
    }

    public LscpUniqSNo clone()
    {
        LscpUniqSNo c = null;
        try
        {
            c = (LscpUniqSNo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.persistenceSno);
        ostr.writeLong(this.bdSNo);
        ostr.writeLong(this.time);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.persistenceSno = istr.readLong();
        this.bdSNo = istr.readLong();
        this.time = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, LscpUniqSNo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public LscpUniqSNo ice_read(com.zeroc.Ice.InputStream istr)
    {
        LscpUniqSNo v = new LscpUniqSNo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LscpUniqSNo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LscpUniqSNo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(24);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<LscpUniqSNo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(LscpUniqSNo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final LscpUniqSNo _nullMarshalValue = new LscpUniqSNo();

    public static final long serialVersionUID = -1024384892L;
}
