// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEELscpProtocal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class LscpGetSaltReq implements Cloneable,
                                       java.io.Serializable
{
    public String usrname;

    public String getUsrname()
    {
        return usrname;
    }

    public void setUsrname(String usrname)
    {
        this.usrname = usrname;
    }

    public LscpAuthType lscpAuthType;

    public LscpAuthType getLscpAuthType()
    {
        return lscpAuthType;
    }

    public void setLscpAuthType(LscpAuthType lscpAuthType)
    {
        this.lscpAuthType = lscpAuthType;
    }

    public short pwdLen;

    public short getPwdLen()
    {
        return pwdLen;
    }

    public void setPwdLen(short pwdLen)
    {
        this.pwdLen = pwdLen;
    }

    public String pwd;

    public String getPwd()
    {
        return pwd;
    }

    public void setPwd(String pwd)
    {
        this.pwd = pwd;
    }

    public LscpGetSaltReq()
    {
        this.usrname = "";
        this.lscpAuthType = LscpAuthType.PSW_TYPE_MD5;
        this.pwdLen = 0;
        this.pwd = "";
    }

    public LscpGetSaltReq(String usrname, LscpAuthType lscpAuthType, short pwdLen, String pwd)
    {
        this.usrname = usrname;
        this.lscpAuthType = lscpAuthType;
        this.pwdLen = pwdLen;
        this.pwd = pwd;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LscpGetSaltReq r = null;
        if(rhs instanceof LscpGetSaltReq)
        {
            r = (LscpGetSaltReq)rhs;
        }

        if(r != null)
        {
            if(this.usrname != r.usrname)
            {
                if(this.usrname == null || r.usrname == null || !this.usrname.equals(r.usrname))
                {
                    return false;
                }
            }
            if(this.lscpAuthType != r.lscpAuthType)
            {
                if(this.lscpAuthType == null || r.lscpAuthType == null || !this.lscpAuthType.equals(r.lscpAuthType))
                {
                    return false;
                }
            }
            if(this.pwdLen != r.pwdLen)
            {
                return false;
            }
            if(this.pwd != r.pwd)
            {
                if(this.pwd == null || r.pwd == null || !this.pwd.equals(r.pwd))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::LscpGetSaltReq");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, usrname);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lscpAuthType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pwdLen);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pwd);
        return h_;
    }

    public LscpGetSaltReq clone()
    {
        LscpGetSaltReq c = null;
        try
        {
            c = (LscpGetSaltReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.usrname);
        LscpAuthType.ice_write(ostr, this.lscpAuthType);
        ostr.writeShort(this.pwdLen);
        ostr.writeString(this.pwd);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.usrname = istr.readString();
        this.lscpAuthType = LscpAuthType.ice_read(istr);
        this.pwdLen = istr.readShort();
        this.pwd = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, LscpGetSaltReq v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public LscpGetSaltReq ice_read(com.zeroc.Ice.InputStream istr)
    {
        LscpGetSaltReq v = new LscpGetSaltReq();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LscpGetSaltReq> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LscpGetSaltReq v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<LscpGetSaltReq> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(LscpGetSaltReq.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final LscpGetSaltReq _nullMarshalValue = new LscpGetSaltReq();

    public static final long serialVersionUID = -715203292L;
}
