// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEELscpProtocal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public enum LscpRTEventType implements java.io.Serializable
{
    E_RTEVENT_POWER_ON(257),
    E_RTEVENT_POWER_OFF(513);

    public int value()
    {
        return _value;
    }

    public static LscpRTEventType valueOf(int v)
    {
        switch(v)
        {
        case 257:
            return E_RTEVENT_POWER_ON;
        case 513:
            return E_RTEVENT_POWER_OFF;
        }
        return null;
    }

    private LscpRTEventType(int v)
    {
        _value = v;
    }

    public void ice_write(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeEnum(_value, 513);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, LscpRTEventType v)
    {
        if(v == null)
        {
            ostr.writeEnum(LscpRTEventType.E_RTEVENT_POWER_ON.value(), 513);
        }
        else
        {
            ostr.writeEnum(v.value(), 513);
        }
    }

    public static LscpRTEventType ice_read(com.zeroc.Ice.InputStream istr)
    {
        int v = istr.readEnum(513);
        return validate(v);
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LscpRTEventType> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    public static void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LscpRTEventType v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            ice_write(ostr, v);
        }
    }

    public static java.util.Optional<LscpRTEventType> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.Size))
        {
            return java.util.Optional.of(ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static LscpRTEventType validate(int v)
    {
        final LscpRTEventType e = valueOf(v);
        if(e == null)
        {
            throw new com.zeroc.Ice.MarshalException("enumerator value " + v + " is out of range");
        }
        return e;
    }

    private final int _value;
}
