// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEEDCMeta.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class OrderByPair implements Cloneable,
                                    java.io.Serializable
{
    public DCColumnType dcColumnType;

    public DCColumnType getDcColumnType()
    {
        return dcColumnType;
    }

    public void setDcColumnType(DCColumnType dcColumnType)
    {
        this.dcColumnType = dcColumnType;
    }

    public OrderByMode orderByMode;

    public OrderByMode getOrderByMode()
    {
        return orderByMode;
    }

    public void setOrderByMode(OrderByMode orderByMode)
    {
        this.orderByMode = orderByMode;
    }

    public OrderByPair()
    {
        this.dcColumnType = DCColumnType.E_COLUMN_ERROR;
        this.orderByMode = OrderByMode.E_ORDERBYMODE_ASC;
    }

    public OrderByPair(DCColumnType dcColumnType, OrderByMode orderByMode)
    {
        this.dcColumnType = dcColumnType;
        this.orderByMode = orderByMode;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        OrderByPair r = null;
        if(rhs instanceof OrderByPair)
        {
            r = (OrderByPair)rhs;
        }

        if(r != null)
        {
            if(this.dcColumnType != r.dcColumnType)
            {
                if(this.dcColumnType == null || r.dcColumnType == null || !this.dcColumnType.equals(r.dcColumnType))
                {
                    return false;
                }
            }
            if(this.orderByMode != r.orderByMode)
            {
                if(this.orderByMode == null || r.orderByMode == null || !this.orderByMode.equals(r.orderByMode))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::OrderByPair");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, dcColumnType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orderByMode);
        return h_;
    }

    public OrderByPair clone()
    {
        OrderByPair c = null;
        try
        {
            c = (OrderByPair)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        DCColumnType.ice_write(ostr, this.dcColumnType);
        OrderByMode.ice_write(ostr, this.orderByMode);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.dcColumnType = DCColumnType.ice_read(istr);
        this.orderByMode = OrderByMode.ice_read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, OrderByPair v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public OrderByPair ice_read(com.zeroc.Ice.InputStream istr)
    {
        OrderByPair v = new OrderByPair();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<OrderByPair> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, OrderByPair v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<OrderByPair> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(OrderByPair.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final OrderByPair _nullMarshalValue = new OrderByPair();

    public static final long serialVersionUID = 429318074L;
}
