// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `TEEENtripProtocal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.teee.referencestation.rpc.ice.teee;

public class SvrPushRTCMReq implements Cloneable,
                                       java.io.Serializable
{
    public String sRTCM;

    public String getSRTCM()
    {
        return sRTCM;
    }

    public void setSRTCM(String sRTCM)
    {
        this.sRTCM = sRTCM;
    }

    public SvrPushRTCMReq()
    {
        this.sRTCM = "";
    }

    public SvrPushRTCMReq(String sRTCM)
    {
        this.sRTCM = sRTCM;
    }

    public boolean equals(Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SvrPushRTCMReq r = null;
        if(rhs instanceof SvrPushRTCMReq)
        {
            r = (SvrPushRTCMReq)rhs;
        }

        if(r != null)
        {
            if(this.sRTCM != r.sRTCM)
            {
                if(this.sRTCM == null || r.sRTCM == null || !this.sRTCM.equals(r.sRTCM))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::teee::SvrPushRTCMReq");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sRTCM);
        return h_;
    }

    public SvrPushRTCMReq clone()
    {
        SvrPushRTCMReq c = null;
        try
        {
            c = (SvrPushRTCMReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.sRTCM);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.sRTCM = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, SvrPushRTCMReq v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public SvrPushRTCMReq ice_read(com.zeroc.Ice.InputStream istr)
    {
        SvrPushRTCMReq v = new SvrPushRTCMReq();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SvrPushRTCMReq> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, SvrPushRTCMReq v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<SvrPushRTCMReq> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(SvrPushRTCMReq.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final SvrPushRTCMReq _nullMarshalValue = new SvrPushRTCMReq();

    public static final long serialVersionUID = -564173919L;
}
